name: Build Obsidian Plugin

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.1

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: |
          # Build web package without database migrations in CI
          cd packages/web && pnpm build:ci && cd ../..
          # Build other packages
          cd packages/plugin && pnpm build && cd ../..
          cd packages/landing && pnpm build 2>/dev/null || true && cd ../..
          cd packages/release-notes && pnpm build 2>/dev/null || true && cd ../..
